@NonCPS
def jsonParser(def json) {
    new groovy.json.JsonSlurperClassic().parse(json)
}

def doRelease(exoUser, jenkinsNodeUser, jiraID, project, releaseCMD, isInParallel) {

   def volume_name = "${jiraID}-${project.name}-workspace"
   def container_name = "${jiraID}-${project.name}"
   def container_run_option = ""
   def docker_image = "${project.container.image}"

   // Create the right command to run in the container
   if (releaseCMD == "start"){
        echo "Create volume ${volume_name}"
        sh "sudo docker volume create --name=${volume_name}"
        container_command = "release-start ${project.name} ${jiraID}"
   } else if (releaseCMD == "validate"){
       container_command = "release-validate ${jiraID}"
   } else if (releaseCMD == "catalog-from-url"){
       container_command = "catalog-from-url ${jiraID}"
   } else if (releaseCMD == "release-continue-from nexus:create"){
       container_command = "release-continue-from nexus:create"
   } else if (releaseCMD == "release-continue-from nexus:deploy"){
       container_command = "release-continue-from nexus:deploy"
   } else if (releaseCMD == "release-continue-from nexus:close"){
       container_command = "release-continue-from nexus:close"
   }

   if (isInParallel == "true"){
       container_run_option = "-d"
   }

   stage "Container ${container_name}"
   sh "sudo docker run --rm ${container_run_option} -v /opt/${jenkinsNodeUser}/.gnupg/pubring.gpg:/home/ciagent/.gnupg/pubring.gpg:ro \
        -v /opt/${jenkinsNodeUser}/.gnupg/secring.gpg:/home/ciagent/.gnupg/secring.gpg:ro \
        -v /opt/${jenkinsNodeUser}/.gnupg/gpg.conf:/home/ciagent/.gnupg/gpg.conf:ro \
        -v /opt/${jenkinsNodeUser}/.ssh/id_rsa:/home/ciagent/.ssh/id_rsa:ro \
        --env-file /opt/${jenkinsNodeUser}/.eXo/Release/exo-release.properties \
        -e exo_user=${exoUser} \
        -e CATALOG_BASE_URL=${CATALOG_BASE_URL} \
        -v ${volume_name}:/opt/exo-release/workspace \
        -v ${jiraID}-m2_cache:/home/ciagent/.m2/repository \
        --name ${container_name} \
        ${docker_image} \
        \"${container_command}\""
}

// Read Datas from JSON Catalog and executes releases
def doReleases(exoUser, jenkinsNodeUser, jiraID, projectsToRelease, releaseCMD, isInParallel) {

   def JSONCatalog = new URL("${CATALOG_BASE_URL}/${JIRA_ID}.json")
   def catalog = jsonParser(JSONCatalog.newReader())

    echo "Number of Projects in Catalog: ${catalog.size}"
    // Loop first on projectsToRelease to keep the order
    for (i = 0; i < projectsToRelease.length; i++) {
         def projectName = projectsToRelease[i];
         for (j = 0; j < catalog.size; j++) {
             if (catalog[j].name == projectName) {
                doRelease(exoUser, jenkinsNodeUser, jiraID, catalog[j], releaseCMD, isInParallel)
             }
         }
    }
}

// Execute Release on Jenkins Slave with Docker
node('docker') {

  // Init parameters
  stage "Check Release parameters"
  def jiraID = "${JIRA_ID}"
  def releaseCMD = "${RELEASE_CMD}"
  def p = "${PROJECTS}"
  def projectsToRelease = p.split(',')
  def isInParallel = "${RELEASE_PROJECTS_IN_PARALLEL}"
  def jenkinsNodeUser = "${JENKINS_NODE_USER}"
  def exoUser = "${BUILD_USER_ID}"
  echo "* Projects: ${PROJECTS}"
  echo "* Command: ${RELEASE_CMD}"
  echo "* Projects: ${PROJECTS}"
  echo "* Releases in Parallel? ${isInParallel}"

  //Create m2 cache volume for the release
  stage "${JIRA_ID}-m2_cache"
  sh "sudo docker volume create --name ${JIRA_ID}-m2_cache --driver local --opt o=uid=1000"

  doReleases(exoUser, jenkinsNodeUser, jiraID, projectsToRelease, releaseCMD, isInParallel)
}
